# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        enabled: true
        cookie_secure: auto   # ⛔ surtout pas "true" en HTTP
        cookie_samesite: lax
        cookie_path: /
        # cookie_name: PHPSESSID   # (optionnel) laisse par défaut si tu veux

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

